# Generated by Django 5.1.1 on 2024-09-19 05:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_book', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('release_year', models.DateField()),
                ('state', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('publishing_company', models.CharField(max_length=200)),
            ],
        ),
    ]
